starts = [
	'You seem angry...What\'s the matter?',
	'I\'m really interested in learning more about your worldview. Tell me more.',
	'That\'s a really interesting take on the issue. Can you tell me more?',
]

all = [
	'If you say so...',
	'I mean, if you\'re sure about it...',
	'Sorry, Can you be more specific?',
	'Sorry, I\'m not sure what you mean. Can you elaborate?',
	'I never thought about it that way before.',
	'I never really gave it much thought. I guess you\'re right.',
	'I\'m sorry, could you clarify that a bit?',
	'Uh, I agree entirely...',
	'I understand. I\'m not bothering you, am I? I\'m sorry for asking so many questions.',
	'I see...I think I understand your point.',
	'I get where you\'re coming from. That makes sense.',
	'That seems reasonable.',
	'That sounds right, I suppose.',
	'That makes sense, I guess.',
	'Oh, did I offend you? Please forgive me!',
	'I feel I understand you a lot more now...',
	'Would you like to discuss this more in person sometime? Maybe over a cup of organic tea?',
	'I\'m starting to see your point...can you keep going?',
	'I\'m sorry, could you say that again? I think I\'m just not getting it.',
	'Um...I think I can understand that.',
	'I\'m sorry if I came off wrong. I just want to understand you better.',
	'Sorry if I\'m being nosy. I just really want to learn more about your unique perspective.',
	'That...that sorta makes sense.',
	'Sorry, I guess I\'m not smart enough to understand your point...can you rephrase?',
	'OK, I get it now. That\'s a unique way of seeing things.',
	'I just wanted to say I think your take on the matter is really neat.',
	'I admire your perspective a lot. I think the world would benefit from hearing you out more.',
]